server:
  port: 8888
spring:
  application:
    name: warrenblog
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/warrenblog
    username: root
    password: wjq
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  security:
    salt: 'mszlu!@#'
  servlet:
    multipart:
      max-request-size: 20MB  # 上传文件的总大小限制
      max-file-size: 2MB      # 单个文件的大小限制

qiniu:
  accessKey: tgQV_ryc5cfqNKIlYzHGBYoC8mimc6y8d0Y_r5f4
  accessSecretKey: 0ZoeVjorktOtJ3x0IQXYzXEIoGYq0gk-CM4-6tyo
  bucketName: warren98
  region: huadong

mybatis-plus:
  configuration:
    #mp日志输出
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-prefix: ms_